### ISSUE TITLE
Ephemeral volume creation not synchronized with PV based volume creation

### ISSUE THREAD

**Issue by ykulazhenkov** [dell/csi-baremetal#105]
Ephemeral volume creation happens in node service:
https://github.com/dell/csi-baremetal/blob/e1e5133ff7d4e559dfea8726925636be2c0a62ff/pkg/node/node.go#L431

PV based volumes created in the controller:
https://github.com/dell/csi-baremetal/blob/e1e5133ff7d4e559dfea8726925636be2c0a62ff/pkg/controller/controller.go#L180

These code paths using the same CR in Kubernetes, there is no synchronization between node and controller parts.

**Comment by mishoyama** [comment]
Not relevant anymore with the new AC reservation logic
