### ISSUE TITLE
Can't create Inline volume if there is no StorageClass with provisioner "baremetal-csi"

### ISSUE THREAD

**Issue by ykulazhenkov** [dell/csi-baremetal#128]
Inline volumes do not require storage class. Scheduler extender will fail to handle scheduling request for inline volume if there is not StorageClass with provisioner "baremetal-csi"

`Unable to collect storage classes: there are no any storage classes with provisioner baremetal-csi`

**Comment by mishoyama** [comment]
Inline volumes support to be deprecated - https://github.com/dell/csi-baremetal/issues/822
