### ISSUE TITLE
Failed to pull image "asdrepo.isus.emc.com:9042/baremetal-csi-plugin-extender:0.0.10-288.bc88077"

### ISSUE THREAD

**Issue by yaroslaver** [dell/csi-baremetal#136]
The image baremetal-csi-plugin-extender:0.0.10-288.bc88077 was built and I pushed it to my custom docker hub registry.
But in the helm chart "scheduler-extender" in file values.yaml I can see value "registry: asdrepo.isus.emc.com:9042" without "global".
In installation process command consist of argument "--set global.registry=<your-registry.com>". I think, you should add "global" to values.yaml of the 2nd chart.

**Comment by yaroslaver** [comment]
And question about 3 following images:
1. livenessprobe:v2.1.0
2. csi-node-driver-registrar:v1.0.1-gke.0
3. csi-provisioner:v1.2.2

Should they refer to custom registry? Or they should refer to official/public registry?
Because I have error "Back-off pulling image yaroslaver/livenessprobe:v2.1.0", where yarosalver is my registry.
All this 3 images wasn't built on my machine and I didn't push they to my registry.

**Comment by yaroslaver** [comment]
@mishoyama @rususlasan I tried to solve little issue with global.registry value

**Comment by rususlasan** [comment]
About images that you asked about. These are 3rd-party components that aren't build as a part of csi-baremetal however they should located in you registry as well. You can pull them from another registries and then push to the your, check links below:
livenessprobe - https://kubernetes-csi.github.io/docs/livenessprobe.html
csi-node-driver-registrar - https://kubernetes-csi.github.io/docs/node-driver-registrar.html
csi-provisioner - https://kubernetes-csi.github.io/docs/external-provisioner.html
