### ISSUE TITLE
Readiness probe failed: OCI runtime exec failed: exec failed: container_linux.go:349: starting container process cause "exec format error": unknown

### ISSUE THREAD

**Issue by yaroslaver** [dell/csi-baremetal#137]
After successfully image pulling I have this warning with reason "unhealthy" on every Pod which were created by 1st helm chart.

**Comment by mishoyama** [comment]
@yaroslaver please provide logs and extra details on your setup.

**Comment by yaroslaver** [comment]
My local machine:

OS: Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-48-generic x86_64)

Docker: 19.03.13, build 4484c46d9d

kubectl: Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:18:22Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

go: go1.15.3 linux/amd64

helm: version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}

protoc: libprotoc 3.11.0 (I used install commands from Makefile)


On nodes (VMs): 

OS: Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-121-generic x86_64)

Docker: 19.03.12 build 48a66213fe

Steps to reproduce:
All commands was executed on my local machine

1. REGISTRY=yaroslaver make generate-api build images
yaroslaver - my registry on docker hub

2. docker pull k8s.gcr.io/sig-storage/livenessprobe:v2.1.0
3. docker pull quay.io/k8scsi/csi-node-driver-registrar:v1.0.1
4. docker pull quay.io/k8scsi/csi-provisioner:v1.2.2
Downloaded missing images

5. Tagged all images with correct name (like yaroslaver/livenessprobe and so on)
6. Pushed all images to my docker hub public registry

8. helm install csi-baremetal baremetal-csi-plugin --set global.registry=yaroslaver --set image.tag=0.0.10-288.bc88077 --set feature.extender=true

Logs:
![image](https://user-images.githubusercontent.com/43792992/97218923-603f4280-17da-11eb-8537-9007888d7b4c.png)
![image](https://user-images.githubusercontent.com/43792992/97219200-b7451780-17da-11eb-982a-341d3162d4a0.png)
kubectl describe po baremetal-csi-controller-774c867589-6t7t9
![image](https://user-images.githubusercontent.com/43792992/97219383-fd9a7680-17da-11eb-895e-7022a481a70f.png)
![image](https://user-images.githubusercontent.com/43792992/97219513-2ae72480-17db-11eb-97d2-47b1947dd655.png)
![image](https://user-images.githubusercontent.com/43792992/97219607-4a7e4d00-17db-11eb-9466-679763a2e33d.png)

kubectl describe po baremetal-csi-node-45b2n
![image](https://user-images.githubusercontent.com/43792992/97219823-9e893180-17db-11eb-80d2-51e9b37b3153.png)
![image](https://user-images.githubusercontent.com/43792992/97219916-c11b4a80-17db-11eb-8f03-eca64c921a06.png)
![image](https://user-images.githubusercontent.com/43792992/97219980-dabc9200-17db-11eb-988b-e02cd66a96bc.png)
![image](https://user-images.githubusercontent.com/43792992/97220042-ed36cb80-17db-11eb-8787-795baf42e778.png)

Some Storage Classes:
![image](https://user-images.githubusercontent.com/43792992/97220253-3d159280-17dc-11eb-8e35-e66ef13828d4.png)

kubectl describe CSIDriver baremetal-csi
![image](https://user-images.githubusercontent.com/43792992/97220342-633b3280-17dc-11eb-8d86-334849d29b62.png)

**Comment by natalya-revtova** [comment]
I have the same problem

**Comment by rususlasan** [comment]
File health_probe was moved to another location. In makefile in curl command there wasn't flag --location that allow curl to retrieve file from new address. Fix will be merged soon - https://github.com/dell/csi-baremetal/pull/148.

**Comment by rususlasan** [comment]
Fix was merged
