### ISSUE TITLE
Invalid logic in "discoverAvailableCapacity" function

### ISSUE THREAD

**Issue by ykulazhenkov** [dell/csi-baremetal#235]
## Invalid logic in "discoverAvailableCapacity" function

If Volume exist on drive we handle this situation incorrectly. We don't expect that Volume CR and AvailableCapacity CR can exist for the Drive at the same time. But now it is absolutely valid situation, because we don't remove AvailableCapacity CR after we created Volume anymore, we just set AvailableCapacity to zero.

If there is a volume on driver we will have ```
[WARN] [VolumeManager] [discoverAvailableCapacity] There is Volume CR that points on same drive 3760b7ca-7275-41fb-920e-eccd545608b7 as AC b65f4779-b9cb-4c8a-95cc-be0e83a7b8ba```
Warning message in log and always try to do unnecessary AC CR update.

Function https://github.com/dell/csi-baremetal/blob/3409cf7a1ab70b031cfae4c4b431b362576186c1/pkg/node/volumemgr.go#L772 should be modified to ignore AvailableCapacity with zero size.

**Comment by ykulazhenkov** [comment]
I found another problem with this function. Race condition possible between this function and volume deletion procedure in csi-controller. AC size increased by volume deletion procedure can be zeroed by this function.

**Comment by mishoyama** [comment]
Not relevant anymore
