### ISSUE TITLE
E2E tests failed when scheduler patcher was killed by SIGKILL

### ISSUE THREAD

**Issue by mishoyama** [dell/csi-baremetal#236]
1. Deploy CSI
2. Kill patcher pod to prevent configuration restore
3. Try to run e2e tests - failed with scheduler not restarted error

**Comment by ykulazhenkov** [comment]
We have `bm-wait-scheduler-restart` option for e2e tests which can be used as workaround for this problem.
https://github.com/dell/csi-baremetal/blob/1bac047c625360599acbb3a4b57a48a7ed558eb9/test/e2e/baremetal_e2e_test.go#L45

**Comment by mishoyama** [comment]
This issue was addressed during code refactoring
