### ISSUE TITLE
Endpoints for extender verbs should be passed as parameters

### ISSUE THREAD

**Issue by rususlasan** [dell/csi-baremetal#78]
These values are defined in [patcher-configmap.yaml](https://github.com/dell/csi-baremetal/blob/master/charts/scheduler-extender/templates/patcher-configmap.yaml) config file and should be passed as parameters.

https://github.com/dell/csi-baremetal/blob/2aff329efef43e13c4cd90f3a0377dba2c6ca733/cmd/scheduling/extender/main.go#L23-L27

**Comment by mishoyama** [comment]
Not relevant anymore
