### ISSUE TITLE
Map k8s storage classes on structures storage classes

### ISSUE THREAD

**Issue by rususlasan** [dell/csi-baremetal#84]
Volume CR spec has storage class filed in which values like HDD, SSD etc are stored. Also during plugin installation k8s storage classes baremetal-csi-sc-hdd, baremetal-csi-sc-ssd etc are installed. Need to implement logic for switching between these storage classes. It is need to scheduler extender to make conversion between storage classes from pods volumes requests and storage classes in AC.

**Comment by mishoyama** [comment]
Not relevant anymore
