### ISSUE TITLE
CSI Node Pod crash observed after scale down and scale up of Atlantic cluster

### ISSUE THREAD

**Issue by CraneShiEMC** [dell/csi-baremetal#885]
**Describe the bug**
CSI Node Pod crash observed after scale down and scale up of Atlantic cluster.

**Environment (please complete the following information):**
 - Hardware: Any
 - OS: Any
 - Version: 1.1.0
 - Platform: Atlantic

**To Reproduce**

1. Taint 1 k8s node
2. Wait for all other pods on this tainted k8s node except for csi node pod scheduled to other k8s nodes
3. Scale Down the Atlantic k8s cluster by removing this tainted k8s node via Atlantic Platform API
4. Scale Up the Atlantic k8s cluster by adding back the k8s node just removed via Atlantic Platform API

**Expected behavior**
The CSI node pod should be initialized and comes up normally on the k8s node added back.

**Screenshots**
```
hostname1:~/objscale # kubectl get pods -o wide -A | grep hostname7
atlantic metallb-speaker-r7pl8 1/1 Running 0 48m 10.249.232.57 hostname7 <none> <none>
calico-system calico-node-bqqd2 1/1 Running 0 48m 10.249.232.57 hostname7 <none> <none>
csi-ns csi-baremetal-node-5mz5c 3/4 CrashLoopBackOff 10 (3m10s ago) 48m 10.42.200.192 hostname7 <none> <none>
kube-system kube-multus-ds-w8whd 1/1 Running 0 48m 10.249.232.57 hostname7 <none> <none>
kube-system kube-proxy-hostname7 1/1 Running 1 48m 10.249.232.57 hostname7 <none> <none>
kube-system rke2-ingress-nginx-controller-l89xp 1/1 Running 0 48m 10.249.232.57 hostname7 <none> <none>
objectscale-system objectscale-manager-fluent-bit-lz7qc 1/1 Running 0 48m 10.42.200.193 hostname7 <none> <none>
```

**Additional context**

**Comment by rkiselenko** [comment]
Please don't refer our jira issues here.

**Comment by CraneShiEMC** [comment]
> Please don't refer our jira issues here.

OK.
